# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Varun Raveendra
full_name: Varun Raveendra
email: varunraveendra@gmail.com
email2: varun.raveendra@utah.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://varunraveendra.github.io" # the base hostname & protocol for your site
github_username:  varunraveendra
twitter_username: varun_raveendra
linkedin_username: varun-robotics
stackoverflow: varun-raveendra
include: ['_pages']
footer-links-active:
  stackoverflow: false

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
